name: Bug report
description: Create a report to help us improve the LGBT Flag Display Tool
title: "[BUG] "
labels: 
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of what the bug is"
      placeholder: "Describe the bug you encountered..."

  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the behavior"
      placeholder: |
        1. Run command '...'
        2. Use flag '...'
        3. See error

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "A clear and concise description of what you expected to happen"

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What actually happened"

  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      options:
        - Linux
        - macOS
        - Windows
        - Other

  - type: input
    id: terminal
    attributes:
      label: "Terminal Emulator"
      description: "Which terminal emulator are you using? (e.g., xterm, iTerm2, Windows Terminal)"

  - type: input
    id: version
    attributes:
      label: "Tool Version"
      description: "Version of the LGBT Flag Display Tool (use --version to check)"

  - type: textarea
    id: build-info
    attributes:
      label: "Build Information"
      description: "How did you build the tool? (e.g., make, make dev, custom flags)"
      placeholder: |
        Build command used:
        Compiler version:
        Any custom build flags:

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem"

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here"
