name: Feature request
description: Suggest an idea for the LGBT Flag Display Tool
title: "[FEATURE] "
labels: 
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: problem
    attributes:
      label: "Is your feature request related to a problem?"
      description: "A clear and concise description of what the problem is"
      placeholder: "I'm always frustrated when [...]"

  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen"

  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered"

  - type: dropdown
    id: feature-type
    attributes:
      label: "Feature Type"
      description: "What kind of feature are you suggesting?"
      options:
        - New Flag
        - New Command Line Option
        - Display Enhancement
        - Performance Improvement
        - Documentation
        - Other

  - type: textarea
    id: implementation
    attributes:
      label: "Implementation Details"
      description: "Any thoughts on how this feature could be implemented"
      placeholder: |
        - Which files would need to be modified?
        - Any specific technical considerations?
        - Any potential challenges?

  - type: textarea
    id: examples
    attributes:
      label: "Examples"
      description: "If applicable, provide examples of how the feature would be used"
      placeholder: |
        Command line examples:
        Expected output:
        Any relevant screenshots:

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Add any other context or screenshots about the feature request here"
