name: General inquiry
description: Ask a question or make a general comment about the LGBT Flag Display Tool
title: "[INQUIRY] "
labels: 
  - question
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the LGBT Flag Display Tool!

  - type: textarea
    id: question
    attributes:
      label: "Your Question or Comment"
      description: "Please be as specific as possible"
      placeholder: "What would you like to know?"

  - type: dropdown
    id: category
    attributes:
      label: "Category"
      description: "What type of inquiry is this?"
      options:
        - Usage Question
        - Installation Help
        - Documentation Question
        - Contribution Question
        - Other

  - type: textarea
    id: context
    attributes:
      label: "Context"
      description: "Provide any relevant context about your question"
      placeholder: |
        - What are you trying to accomplish?
        - What have you tried so far?
        - Any error messages or unexpected behavior?

  - type: input
    id: version
    attributes:
      label: "Tool Version"
      description: "Version of the LGBT Flag Display Tool (use --version to check)"

  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      options:
        - Linux
        - macOS
        - Windows
        - Other

  - type: textarea
    id: additional
    attributes:
      label: "Additional Information"
      description: "Add any other relevant information here"
