name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install make

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install make -y

      - name: Build
        run: |
          make clean
          make

      - name: Test
        run: |
          ./bin/lgbt --list
          ./bin/lgbt --flag=trans
          ./bin/lgbt --flag=rainbow --matrix=40x20
          ./bin/lgbt --flag=lesbian --border
          ./bin/lgbt --flag=bi --reverse

      - name: Test error handling
        run: |
          ./bin/lgbt --flag=nonexistent || true
          ./bin/lgbt --matrix=invalid || true
          ./bin/lgbt || true 